export const GET_PROVINCES_START = "GET_PROVINCES_START";
export const GET_PROVINCES_SUCCESS = "GET_PROVINCES_SUCCESS";
export const GET_PROVINCES_ERROR = "GET_PROVINCES_ERROR";

export const GET_LOCALITY_START = "GET_LOCALITY_START";
export const GET_LOCALITY_SUCCESS = "GET_LOCALITY_SUCCESS";
export const GET_LOCALITY_ERROR = "GET_LOCALITY_ERROR";